add example use case
Sellsuki/vuex-async-module pull request #13
Opened 2017-11-10 10:28 UTC by jitinics

2017-11-11 06:27 UTC, pangaunn requested changes
เราควรจะแยก repo สำหรับ example ออกไหม
ถ้าเราจะต้องมีไฟล์ boilerplate ของ vue เยอะขนาดนี้

2017-11-13 05:00 UTC, noomerzx commented
ผมว่าไม่ต้องก็ได้มั้งพี่ เพราะคงไม่น่ามี example มากไปกว่านี้ แต่ถ้าอนาคตจะทำเพิ่มไปอีกก็อีกเรื่อง อันนี้ลองดูของ vue official ก็ยัด example มาไว้ในตัวเลย แต่ของมันไม่มี boilerplate เพราะเป็นแบบง่ายๆ แต่จิงๆผมว่าแค่เพิ่ม readme ในแต่ละ example โชว์ไปอีกก็อาจจะยิ่งแจ่ม

https://github.com/vuejs/vue/tree/dev/examples

2017-11-13 06:04 UTC, n9ti commented
ถ้างั้นอาจจะต้องใช้ npm ignore เพื่อคนที่ติดตั้ง lib เราผ่าน npm จะได้ไม่ต้องโหลด code example ลงไปให้หนักเปล่าๆ

2017-11-13 06:11 UTC, jitinics commented
npm ignore มีเขียนไว้แล้วป่าวครับเห็น ignore ยกเว้น dist กับ package

2017-11-14 04:49 UTC, closed without merging